language: cpp
sudo: required
virtualenv:
    system_site_packages: true
git:
    submodules: false
    depth: 1
addons:
    homebrew:
        packages:
            - ccache
            - cmake
        update: true
cache: ccache
matrix:
  include:
    - os: osx
      osx_image: xcode11.2
      compiler: clang
      before_install:
        - git submodule update --init
        - sw_vers
        - python3 -m venv pyenv
        - source pyenv/bin/activate
      install:
        - pip install -r python/requirements.txt
    - os: osx
      osx_image: xcode9.4
      compiler: clang
      before_install:
        - git submodule update --init
        - sw_vers
        - python3 -m venv pyenv
        - source pyenv/bin/activate
      install:
        - pip install -r python/requirements.txt
    - os: osx
      osx_image: xcode9.3
      compiler: clang
      before_install:
        - git submodule update --init
        - sw_vers
        - pip install virtualenv
        - virtualenv pyenv
        - source pyenv/bin/activate
      install:
        - pip install -r python/requirements.txt
    - os: linux
      dist: xenial
      python: "2.7"
      addons:
        apt:
          update: true
          sources:
            - sourceline: ppa:deadsnakes/ppa
          packages:
            - libeigen3-dev
            - libgmp-dev
            - libgmpxx4ldbl
            - libmpfr-dev
            - libboost-dev
            - libboost-thread-dev
            - libtbb-dev
      before_install:
        - git submodule update --init
        # Conda (Miniconda)
        - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - hash -r
        - conda config --set always_yes yes --set changeps1 no
        - conda update -q conda
        # Useful for debugging any issues with conda
        - conda info -a
      install:
        # Create conda enviroment
        - conda create -q -n test-environment python=2.7
        - source activate test-environment
        - conda install cmake
        # info on python executables
        - python --version
        - pip install -r python/requirements.txt

script:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="/usr/local/opt/ccache/libexec:$PATH"; fi
    - ccache --max-size=5.0G
    - ccache -V && ccache --show-stats && ccache --zero-stats
    - ./setup.py build
    - ./setup.py install
    - python -c "import pymesh; import sys; sys.exit(0 if pymesh.test().wasSuccessful() else 1)"

